#! /usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.bash_aliases
ln -s $DOTFILES/setup/.bash_aliases $HOME/.bash_aliases

rm -rf $HOME/.inputrc
ln -s $DOTFILES/setup/.inputrc $HOME/.inputrc

rm -rf $HOME/.vimrc
ln -s $DOTFILES/setup/.vimrc $HOME/.vimrc

rm -rf $HOME/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/

