#! /usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.bash_aliases
ln -s $DOTFILES/setup/.bash_aliases $HOME/.bash_aliases

rm -rf $HOME/.inputrc
ln -s $DOTFILES/setup/.inputrc $HOME/.inputrc

rm -rf $HOME/.vimrc
ln -s $DOTFILES/setup/.vimrc $HOME/.vimrc

rm -rf $HOME/Library/Application\ Support/Sublime\ Text/Packages
ln -s $DOTFILES/sublime/User $HOME/Library/Application\ Support/Sublime\ Text/Packages

# rm -rf $HOME/.config/alacritty
# ln -s $DOTFILES/alacritty $HOME/.config/alacritty
#
# rm -rf $HOME/.tmux.conf
# ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# mkdir -p $HOME/.local/bin

# rm -rf $HOME/.local/bin/t
# ln -s $DOTFILES/scripts/t $HOME/.local/bin

